library(devtools)
library(roxygen2)
#devtools::install_local("D:/project/digestion_SI/ancestral_reconstruction/ASR_test/ASR_0.1.0.0.tar.gz")
library(ASR)
library(ggtree)
library(treeio)
library(ape)
path = "D:/project/digestion_SI/ancestral_reconstruction/Alltest_20250812/"
tree <- read.tree(file.path(path, "output_tree.newick"))
file <- read.csv(file.path(path, "All_module_gene3.csv"))
file <- ASR:::file.handle(tree,file)
ASR:::MPWeight11(tree,file,path,cellname = "All")
ASR:::MPWeight21(tree,file,path,cellname = "T")
ASR:::Wanger(tree,file,path,cellname = "T")
ASR:::REML(tree,file,path,cellname = "T")
